version: '3'

services:
  mongo:
    image: mongo:xenial
    restart: always
    ports:
      - 27017:27017

  app:
    build: ./
    container_name: 'app'
    volumes:
      - .:/code
    ports:
      - 8080:8080
    depends_on:
      - mongo
