version: '3'

services:
  mongo:
    image: mongo:xenial
    restart: always
    ports:
      - 27017:27017

  auth:
    build: ./microservices/auth
    container_name: 'auth'
    ports:
      - 8081:8080

  payments:
    build: ./microservices/payments
    container_name: 'payments'
    ports:
      - 8082:8080

  products:
    build: ./microservices/products
    container_name: 'products'
    ports:
      - 8083:8080

  reports:
    build: ./microservices/reports
    container_name: 'reports'
    ports:
      - 8084:8080

  users:
    build: ./microservices/users
    container_name: 'users'
    ports:
      - 8085:8080

  gateway:
    build: ./microservices/gateway
    container_name: 'gateway'
    ports:
      - 8080:8080
